I am a wrapper for Python 3 exception.

I just hold the traceback of the exception.